[package]
authors = ["Kornel <pornel@pornel.net>"]
description = "Load PNG or JPEG with color profile support"
keywords = ["load_image"]
license = "GPL-3.0+"
name = "load_image"
version = "2.15.1"
edition = "2018"
include = ["src/*.rs", "src/*.icc", "Cargo.toml", "COPYING", "README.md"]
readme = "README.md"
homepage = "https://imageoptim.com/api"

[dependencies]
imgref = "1.9.1"
lcms2 = "5.4.1"
lodepng = "3.4.7"
rexif = "0.7.3"
rgb = "0.8.29"
mozjpeg = "0.9.1"
aom-decode = { version = "0.2.0", optional = true }
num_cpus = { version = "1.13.0", optional = true }
libwebp = { version = "0.1.2", features = ["1_1"], optional = true }
fallible_collections = "0.4.3"

[features]
stat = []

avif = ["aom-decode", "num_cpus"]

webp = ["libwebp"]
webp-static = ["webp", "libwebp/static"]

lcms2-static = ["lcms2/static"]
# old name; do not use
static = ["lcms2-static"]

[lib]
doctest = false
name = "load_image"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
