[package]
authors = ["Kornel <pornel@pornel.net>"]
description = "Load PNG or JPEG with color profile support"
keywords = ["load_image"]
license = "GPL-3.0+"
name = "load_image"
version = "2.12.2"
edition = "2018"
include = ["src/*.rs", "src/*.icc", "Cargo.toml", "COPYING", "README.md"]
readme = "README.md"
homepage = "https://imageoptim.com/api"

[dependencies]
imgref = "1.9.0"
lcms2 = "5.4.1"
lodepng = "3.4.5"
rexif = "0.7.0"
rgb = "0.8.27"
mozjpeg = "0.9.0"

[features]
static = ["lcms2/static"]
stat = []

[lib]
doctest = false
name = "load_image"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
