[package]
authors = ["Kornel <pornel@pornel.net>"]
description = "Load PNG or JPEG with color profile support"
keywords = ["load_image"]
license = "GPL-3.0+"
name = "load_image"
version = "3.0.0"
edition = "2021"
include = ["src/*.rs", "src/*.icc", "Cargo.toml", "COPYING", "README.md"]
readme = "README.md"
homepage = "https://imageoptim.com/api"
categories = ["multimedia::images"]

[dependencies]
imgref = "1.9.4"
lcms2 = "5.5.0"
lodepng = "3.7.0"
rgb = "0.8.34"
rexif = { version = "0.7.3", optional = true }
mozjpeg = { version = "0.9.4", optional = true }
aom-decode = { version = "0.2.4", optional = true }
num_cpus = { version = "1.13.1", optional = true }
libwebp = { version = "0.1.2", features = ["1_1"], optional = true }
jpeg-decoder = { version = "0.2.6", optional = true }
bytemuck = "1.12.1"
quick-error = "2.0.1"

[features]
default = ["jpeg"]
mozjpeg = ["dep:mozjpeg", "dep:rexif"]
jpeg = ["dep:jpeg-decoder", "dep:rexif"]
stat = []

avif = ["dep:aom-decode", "dep:num_cpus"]

webp = ["dep:libwebp"]
webp-static = ["webp", "libwebp?/static"]

lcms2-static = ["lcms2/static"]
# old name; do not use
static = ["lcms2-static"]

[lib]
doctest = false
name = "load_image"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[badges]
maintenance = { status = "actively-developed" }
